//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primitives
{
    
    internal partial class Resource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource.manager == null))
                {
                    Resource.manager = new System.Resources.ResourceManager("Primitives.Resource", typeof(Resource).Assembly);
                }
                return Resource.manager;
            }
        }
        internal static byte[] GetBitmap(Resource.BitmapResources id)
        {
            return ((byte[])(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static nanoFramework.UI.Font GetFont(Resource.FontResources id)
        {
            return ((nanoFramework.UI.Font)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resource.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            b3 = -28145,
            b4 = -27204,
            b9 = -26019,
            Yellow_flower = -24067,
            b5 = -20880,
            Birds = -14105,
            b2 = -8183,
            SoccerBall = 5884,
            b1 = 10850,
            Image1 = 21113,
            b6 = 26679,
            b7 = 31481,
            b8 = 31966,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            strnSmallFont = -19509,
            strComicSansMS16 = -18892,
            strNinaFont = 10925,
            strCourierRegular10 = 19139,
            strSegoeUIRegular12 = 25622,
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            ComicSansMS16 = -18137,
            SegoeUIRegular12 = 11243,
            small = 13070,
            NinaB = 18060,
            CourierRegular10 = 27752,
            MatrixFont = 28174,
        }
    }
}
